### ISSUE TITLE
Fazer preservaçao digital de arquivos do Perú (Cusco)

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/digital-preservation-PE#2]

**Comment by ThierryAJean** [comment]
Peter sugere que Igor e Carlos, talvez com ajuda do Claiton, possa fazer estas operações de "join"

**Comment by IgorEliezer** [comment]
Teste de PE-Cusco.
![image](https://user-images.githubusercontent.com/4673289/133160900-a1290463-672d-41b6-8817-93fa663da3bc.png)

**Comment by ThierryAJean** [comment]
@crebollobr Fazer a associação do numeros prediais com os numeros de instalação de água. @IgorEliezer ajuda.

**Comment by ThierryAJean** [comment]
@crebollobr Pfv Testar e verificar o Yaml
